// Smart Report V2 - Two-Page Approach
// Page 1: Generated locally with PDF.co (letterhead, lab/patient info, test scope)
// Page 2+: Generated by Gamma AI (clean results, no background/signature)
// Final: Merged using PDF.co /pdf/merge

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.38.4'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Fallback to hardcoded key if env var not set (same as generate-smart-report)
const GAMMA_API_KEY = Deno.env.get('GAMMA_API_KEY') || 'sk-gamma-lTDqDYXVz6QTreO50hMEnyTnREmjGOMyqgcoYOwpvk'
const PDFCO_API_KEY = Deno.env.get('PDFCO_API_KEY') || ''
const CUSTOM_REPORTS_DOMAIN = Deno.env.get('CUSTOM_STORAGE_DOMAIN') || ''

/**
 * Get public URL for storage file with custom domain support
 * (Same pattern as generate-pdf-letterhead)
 */
function getPublicStorageUrl(bucket: string, path: string): string {
  if (bucket === 'reports' && CUSTOM_REPORTS_DOMAIN) {
    const cleanPath = path.startsWith('/') ? path.slice(1) : path
    return `${CUSTOM_REPORTS_DOMAIN}/${cleanPath}`
  }

  // Fallback to Supabase default URL
  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
  return `${supabaseUrl}/storage/v1/object/public/${bucket}/${path}`
}

// ============================================================
// LETTERHEAD FETCHING (adapted from headerFooterHelper.ts)
// ============================================================

async function fetchLetterheadBackgroundForOrder(
  supabase: any,
  orderId: string,
  labId: string
): Promise<string | null> {
  try {
    console.log('[LETTERHEAD] Fetching for order:', orderId)

    // Get order context
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .select('account_id, location_id')
      .eq('id', orderId)
      .single()

    if (orderError) {
      console.log('[LETTERHEAD] Error fetching order, falling back to lab-level')
      return fetchLabLetterhead(supabase, labId)
    }

    // Priority 1: B2B Account header
    if (order?.account_id) {
      const accountHeader = await getAttachmentHeader(supabase, 'account', order.account_id)
      if (accountHeader) {
        console.log('[LETTERHEAD] Using B2B account header')
        return accountHeader
      }
    }

    // Priority 2: Location header
    if (order?.location_id) {
      const locationHeader = await getAttachmentHeader(supabase, 'location', order.location_id)
      if (locationHeader) {
        console.log('[LETTERHEAD] Using location header')
        return locationHeader
      }
    }

    // Priority 3: Lab-level
    return fetchLabLetterhead(supabase, labId)
  } catch (error) {
    console.error('[LETTERHEAD] Error:', error)
    return fetchLabLetterhead(supabase, labId)
  }
}

async function getAttachmentHeader(
  supabase: any,
  entityType: string,
  entityId: string
): Promise<string | null> {
  try {
    const { data: attachment, error } = await supabase
      .from('attachments')
      .select('file_url, imagekit_url')
      .eq('entity_type', entityType)
      .eq('entity_id', entityId)
      .eq('attachment_type', 'header')
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (error || !attachment) return null
    return attachment.imagekit_url || attachment.file_url
  } catch {
    return null
  }
}

async function fetchLabLetterhead(supabase: any, labId: string): Promise<string | null> {
  try {
    const { data: asset, error } = await supabase
      .from('lab_branding_assets')
      .select('imagekit_url, file_url')
      .eq('lab_id', labId)
      .eq('asset_type', 'header')
      .eq('is_active', true)
      .eq('is_default', true)
      .single()

    if (error || !asset) return null
    return asset.imagekit_url || asset.file_url
  } catch {
    return null
  }
}

// ============================================================
// FIRST PAGE HTML BUILDER
// ============================================================

interface FirstPageContext {
  labName: string
  labAddress: string
  labPhone: string
  labEmail: string
  patientName: string
  patientAge: string
  patientGender: string
  patientPhone: string
  sampleId: string
  orderDate: string
  collectionDate: string
  doctorName: string
  testGroups: { id: string; name: string }[]
  // Signatory info
  signatoryName: string
  signatoryImageUrl: string
}

function buildFirstPageHtml(ctx: FirstPageContext, letterheadUrl: string | null): string {
  const testChips = ctx.testGroups
    .map(g => `<span class="test-chip">${g.name}</span>`)
    .join('')

  const letterheadStyle = letterheadUrl
    ? `
      #page-bg {
        position: fixed;
        top: 0;
        left: 0;
        width: 210mm;
        height: 297mm;
        z-index: 0;
        pointer-events: none;
        background-image: url('${letterheadUrl}');
        background-repeat: no-repeat;
        background-position: top left;
        background-size: 210mm 297mm;
      }
    `
    : ''

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * { box-sizing: border-box; margin: 0; padding: 0; }

    @page {
      size: A4;
      margin: 0;
    }

    body {
      font-family: 'Inter', Arial, sans-serif;
      color: #1f2937;
      line-height: 1.6;
      background: transparent;
      width: 210mm;
      height: 297mm;
    }

    ${letterheadStyle}

    .cover-page {
      position: relative;
      z-index: 1;
      min-height: 297mm;
      padding: 40px;
      background: transparent;
    }

    .lab-section {
      text-align: center;
      margin-bottom: 30px;
      padding-top: ${letterheadUrl ? '120px' : '40px'};
    }

    .lab-name {
      font-size: 26px;
      font-weight: 700;
      color: #1e40af;
      margin-bottom: 8px;
    }

    .lab-contact {
      font-size: 13px;
      color: #6b7280;
    }

    .report-title {
      text-align: center;
      margin: 40px 0 35px;
    }

    .report-title h1 {
      font-size: 32px;
      font-weight: 700;
      color: #111827;
      margin-bottom: 12px;
    }

    .smart-badge {
      display: inline-block;
      background: linear-gradient(135deg, #4f46e5, #7c3aed);
      color: white;
      padding: 8px 20px;
      border-radius: 25px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 1px;
    }

    .info-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
      margin: 35px 20px;
    }

    .info-card {
      background: rgba(248, 250, 252, 0.95);
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 20px 24px;
    }

    .info-card h3 {
      font-size: 13px;
      font-weight: 600;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 14px;
      border-bottom: 2px solid #3b82f6;
      padding-bottom: 8px;
    }

    .info-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
      padding: 4px 0;
    }

    .info-row:last-child {
      margin-bottom: 0;
    }

    .info-label {
      color: #6b7280;
      font-size: 13px;
    }

    .info-value {
      font-weight: 600;
      color: #111827;
      font-size: 13px;
      text-align: right;
    }

    .test-scope {
      margin: 45px 20px 30px;
      text-align: center;
    }

    .test-scope h3 {
      font-size: 15px;
      font-weight: 600;
      color: #374151;
      margin-bottom: 20px;
    }

    .test-list {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      gap: 12px;
    }

    .test-chip {
      background: linear-gradient(135deg, #eff6ff, #dbeafe);
      border: 1px solid #93c5fd;
      color: #1e40af;
      padding: 10px 18px;
      border-radius: 10px;
      font-size: 13px;
      font-weight: 500;
    }

    .signatory-section {
      margin: 40px 20px 20px;
      display: flex;
      justify-content: flex-end;
    }

    .signatory-box {
      text-align: center;
      padding: 15px 30px;
    }

    .signature-img {
      max-height: 60px;
      max-width: 150px;
      object-fit: contain;
      margin-bottom: 8px;
    }

    .signatory-name {
      font-size: 13px;
      font-weight: 600;
      color: #1f2937;
      border-top: 1px solid #d1d5db;
      padding-top: 8px;
    }

    .disclaimer {
      position: absolute;
      bottom: 50px;
      left: 40px;
      right: 40px;
      text-align: center;
      font-size: 11px;
      color: #9ca3af;
      border-top: 1px solid #e5e7eb;
      padding-top: 20px;
    }
  </style>
</head>
<body>
  ${letterheadUrl ? '<div id="page-bg"></div>' : ''}
  <div class="cover-page">
    <div class="lab-section">
      <div class="lab-name">${ctx.labName || 'Laboratory'}</div>
      <div class="lab-contact">${ctx.labAddress || ''}</div>
      ${ctx.labPhone || ctx.labEmail ? `<div class="lab-contact">${[ctx.labPhone, ctx.labEmail].filter(Boolean).join(' | ')}</div>` : ''}
    </div>

    <div class="report-title">
      <h1>Laboratory Report</h1>
      <span class="smart-badge">AI Enhanced Analysis</span>
    </div>

    <div class="info-grid">
      <div class="info-card">
        <h3>Patient Information</h3>
        <div class="info-row">
          <span class="info-label">Name</span>
          <span class="info-value">${ctx.patientName || '-'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Age / Gender</span>
          <span class="info-value">${ctx.patientAge || '-'} / ${ctx.patientGender || '-'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Phone</span>
          <span class="info-value">${ctx.patientPhone || '-'}</span>
        </div>
      </div>

      <div class="info-card">
        <h3>Order Details</h3>
        <div class="info-row">
          <span class="info-label">Sample ID</span>
          <span class="info-value">${ctx.sampleId || '-'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Order Date</span>
          <span class="info-value">${ctx.orderDate || '-'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Referring Doctor</span>
          <span class="info-value">${ctx.doctorName || '-'}</span>
        </div>
      </div>
    </div>

    <div class="test-scope">
      <h3>Tests Included in This Report</h3>
      <div class="test-list">
        ${testChips || '<span class="test-chip">Laboratory Tests</span>'}
      </div>
    </div>

    ${ctx.signatoryImageUrl ? `
    <div class="signatory-section">
      <div class="signatory-box">
        <img src="${ctx.signatoryImageUrl}" alt="Signature" class="signature-img" />
        <div class="signatory-name">${ctx.signatoryName || 'Authorized Signatory'}</div>
      </div>
    </div>
    ` : ''}

    <div class="disclaimer">
      This AI-enhanced report provides detailed analysis and clinical insights.<br>
      Please consult your physician for medical interpretation and advice.
    </div>
  </div>
</body>
</html>`
}

// ============================================================
// PDF.CO FIRST PAGE GENERATION
// ============================================================

async function generateFirstPagePdf(html: string): Promise<string> {
  console.log('[FIRST PAGE] Generating PDF with PDF.co...')

  const response = await fetch('https://api.pdf.co/v1/pdf/convert/from/html', {
    method: 'POST',
    headers: {
      'x-api-key': PDFCO_API_KEY,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      html: html,
      name: `smart_report_cover_${Date.now()}.pdf`,
      paperSize: 'A4',
      margins: '0px 0px 0px 0px',
      async: false,
      printBackground: true,
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`PDF.co first page generation failed: ${errorText}`)
  }

  const result = await response.json()

  if (result.error) {
    throw new Error(`PDF.co error: ${result.message}`)
  }

  console.log('[FIRST PAGE] PDF generated:', result.url)
  return result.url
}

// ============================================================
// AI RESULT INTELLIGENCE - Get rich content before Gamma
// ============================================================

interface PatientSummaryResponse {
  health_status: string
  normal_findings_detailed: Array<{
    test_name: string
    value: string
    what_it_measures: string
    your_result_means: string
  }>
  abnormal_findings: Array<{
    test_name: string
    value: string
    status: string
    what_it_measures: string
    explanation: string
    what_to_do: string
    trend?: string
  }>
  needs_consultation: boolean
  consultation_recommendation: string
  health_tips: string[]
  summary_message: string
}

async function getAIPatientSummary(
  testGroups: Array<{ name: string; category: string; result_values: any[] }>,
  patient: { age?: number; gender?: string }
): Promise<PatientSummaryResponse | null> {
  try {
    console.log('[AI] Fetching patient summary from ai-result-intelligence...')

    const AI_ENDPOINT = Deno.env.get('AI_RESULT_INTELLIGENCE_URL') ||
      'https://limsv2.netlify.app/.netlify/functions/ai-result-intelligence'

    const response = await fetch(AI_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'patient_summary',
        test_groups: testGroups,
        language: 'english',
        patient: patient
      })
    })

    if (!response.ok) {
      console.warn('[AI] Patient summary request failed:', response.status)
      return null
    }

    const data = await response.json()
    console.log('[AI] Patient summary received successfully')
    return data
  } catch (error) {
    console.warn('[AI] Failed to get patient summary:', error)
    return null
  }
}

// ============================================================
// GAMMA AI CONTENT GENERATION - ENHANCED
// ============================================================

interface AnalyteData {
  parameter: string
  value: string | number
  unit: string
  referenceRange: string
  flag: string
  interpretation?: string
}

interface TestGroupData {
  id: string
  name: string
  analytes: AnalyteData[]
}

function buildEnhancedGammaInput(
  testGroups: TestGroupData[],
  patientAge: string,
  patientGender: string,
  aiSummary: PatientSummaryResponse | null
): string {
  let inputText = ''

  // ===== SECTION 1: HEALTH OVERVIEW =====
  if (aiSummary?.health_status) {
    inputText += `# Health Overview\n\n`
    inputText += `${aiSummary.health_status}\n\n`
    inputText += `---\n\n`
  }

  // ===== SECTION 2: KEY FINDINGS (Abnormal) =====
  if (aiSummary?.abnormal_findings && aiSummary.abnormal_findings.length > 0) {
    inputText += `# ⚠️ Key Findings Requiring Attention\n\n`

    for (const finding of aiSummary.abnormal_findings) {
      inputText += `## ${finding.test_name}: ${finding.value}\n\n`
      inputText += `**Status:** ${finding.status.toUpperCase()}\n\n`
      inputText += `**What this test measures:** ${finding.what_it_measures}\n\n`
      inputText += `**What your result means:** ${finding.explanation}\n\n`
      inputText += `**Recommended action:** ${finding.what_to_do}\n\n`
      if (finding.trend) {
        inputText += `**Trend:** ${finding.trend}\n\n`
      }
      inputText += `---\n\n`
    }
  }

  // ===== SECTION 3: TEST RESULTS WITH VISUAL INDICATORS =====
  inputText += `# Detailed Test Results\n\n`

  for (const group of testGroups) {
    inputText += `## ${group.name}\n\n`

    // Create visual result cards instead of plain table
    for (const analyte of group.analytes) {
      const isAbnormal = analyte.flag && !['Normal', 'N', 'normal', ''].includes(analyte.flag)
      const statusIcon = isAbnormal ? '🔴' : '🟢'
      const statusText = isAbnormal ? analyte.flag.toUpperCase() : 'NORMAL'

      inputText += `### ${statusIcon} ${analyte.parameter}\n\n`
      inputText += `- **Your Value:** ${analyte.value} ${analyte.unit || ''}\n`
      inputText += `- **Reference Range:** ${analyte.referenceRange || 'Not specified'}\n`
      inputText += `- **Status:** ${statusText}\n\n`

      // Add AI explanation if available
      if (aiSummary) {
        const normalFinding = aiSummary.normal_findings_detailed?.find(
          f => f.test_name.toLowerCase() === analyte.parameter.toLowerCase()
        )
        if (normalFinding) {
          inputText += `> **What this measures:** ${normalFinding.what_it_measures}\n\n`
          inputText += `> **Your result means:** ${normalFinding.your_result_means}\n\n`
        }
      }
    }
    inputText += `---\n\n`
  }

  // ===== SECTION 4: HEALTH RECOMMENDATIONS =====
  if (aiSummary?.health_tips && aiSummary.health_tips.length > 0) {
    inputText += `# 💡 Personalized Health Recommendations\n\n`
    for (const tip of aiSummary.health_tips) {
      inputText += `- ${tip}\n`
    }
    inputText += `\n---\n\n`
  }

  // ===== SECTION 5: CONSULTATION ADVICE =====
  if (aiSummary?.consultation_recommendation) {
    inputText += `# 👨‍⚕️ Doctor's Consultation\n\n`
    inputText += `${aiSummary.consultation_recommendation}\n\n`
  }

  // ===== SECTION 6: CLOSING MESSAGE =====
  if (aiSummary?.summary_message) {
    inputText += `---\n\n`
    inputText += `*${aiSummary.summary_message}*\n`
  }

  // Patient context for any additional AI interpretation
  inputText += `\n---\n**Patient:** ${patientAge || 'Unknown'} year old ${patientGender || 'patient'}\n`

  return inputText
}

// Fallback for when AI summary is not available
function buildBasicGammaInput(testGroups: TestGroupData[], patientAge: string, patientGender: string): string {
  let inputText = '# Laboratory Test Results\n\n'

  for (const group of testGroups) {
    inputText += `## ${group.name}\n\n`

    for (const analyte of group.analytes) {
      const isAbnormal = analyte.flag && !['Normal', 'N', 'normal', ''].includes(analyte.flag)
      const statusIcon = isAbnormal ? '🔴' : '🟢'
      const statusText = isAbnormal ? analyte.flag.toUpperCase() : 'NORMAL'

      inputText += `### ${statusIcon} ${analyte.parameter}\n`
      inputText += `- **Value:** ${analyte.value} ${analyte.unit || ''}\n`
      inputText += `- **Reference:** ${analyte.referenceRange || '-'}\n`
      inputText += `- **Status:** ${statusText}\n\n`
    }
    inputText += `---\n\n`
  }

  inputText += `\n**Patient:** ${patientAge || 'Unknown'} year old ${patientGender || 'patient'}\n`
  inputText += `\nPlease provide clinical interpretation and health recommendations.\n`

  return inputText
}

const GAMMA_INSTRUCTIONS = `
Create a VISUALLY STUNNING, INFOGRAPHIC-STYLE health report. This should look like a modern health app or premium medical report.

═══════════════════════════════════════════════════════════════
DESIGN PHILOSOPHY: Think Fitbit Health Report + Apple Health Summary
═══════════════════════════════════════════════════════════════

VISUAL ELEMENTS TO CREATE:

1. **HEALTH OVERVIEW SECTION** (First Page)
   - Large, welcoming header with gradient background
   - Use a circular or semi-circular GAUGE/METER graphic showing overall health score
   - Health status in large, friendly text
   - Use calming colors: soft blues, greens, whites

2. **KEY FINDINGS CARDS** (For abnormal results)
   - Each abnormal finding gets its own VISUAL CARD
   - Use orange/red warning colors for the card border
   - Include a visual meter showing where the value falls on the reference range
   - Like this:  [====🔴====|----Normal----] for high values
   - Add icon indicators: ⚠️ for warnings, ❗ for critical

3. **TEST RESULTS - VISUAL CARDS** (Not boring tables!)
   For each test parameter, create a VISUAL CARD showing:
   - Parameter name in bold
   - Large value display (like "215 mg/dL" in big text)
   - Visual range indicator/gauge:
     ┌─────────────────────────────────────────┐
     │  [Green Zone] [Yellow] [Red Zone]       │
     │  ────────────────●────────────────────  │
     │        Your Value: 215                  │
     └─────────────────────────────────────────┘
   - Status badge: 🟢 NORMAL or 🟠 BORDERLINE or 🔴 HIGH
   - What this test measures (brief explanation)

4. **HEALTH TIPS SECTION**
   - Use colorful cards with icons
   - Each tip in its own visually distinct box
   - Use lifestyle icons: 🥗 🏃 💧 😴 🧘

5. **CONSULTATION BOX**
   - Distinct call-to-action card
   - Use a light blue background with doctor icon
   - Clear, actionable message

VISUAL STYLING RULES:
- Use LARGE typography for values (32pt+ for main numbers)
- Use progress bars, gauges, meters - NOT plain tables
- Color-code everything: Green=Good, Orange=Caution, Red=Attention
- Round corners, soft shadows, modern card design
- White space is important - don't crowd elements
- Use emoji/icons generously but appropriately

COLOR PALETTE:
- Normal/Good: #10b981 (green)
- Borderline: #f59e0b (amber)
- High/Low: #ef4444 (red)
- Info cards: #3b82f6 (blue)
- Background: #f8fafc (light gray)
- Text: #1f2937 (dark gray)

ABSOLUTELY DO NOT INCLUDE:
- Signatures or doctor names
- Lab headers/footers
- Page numbers
- Stock photos
- Background watermarks

The content I'm sending is PRE-ANALYZED with AI insights.
Render it beautifully with visual data representations.
Make it look like a premium health app report!
`

async function generateGammaContent(inputText: string): Promise<string> {
  console.log('[GAMMA] Starting generation...')
  console.log('[GAMMA] Input length:', inputText.length)

  // 1. Initiate Generation
  const initiateResponse = await fetch('https://public-api.gamma.app/v1.0/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-API-KEY': GAMMA_API_KEY,
      'accept': 'application/json'
    },
    body: JSON.stringify({
      textMode: 'generate',
      inputText: inputText,
      format: 'document',
      themeId: 'wbpgwj9c0ty5wbo', // Clean medical theme
      cardSplit: 'inputTextBreaks',
      additionalInstructions: GAMMA_INSTRUCTIONS,
      exportAs: 'pdf',
      sharingOptions: {
        workspaceAccess: 'edit',
        externalAccess: 'view'
      },
      imageOptions: {
        source: 'noImages' // No stock images
      }
    })
  })

  if (!initiateResponse.ok) {
    const errText = await initiateResponse.text()
    throw new Error(`Gamma API init failed: ${initiateResponse.status} - ${errText}`)
  }

  const initData = await initiateResponse.json()
  const generationId = initData.generationId

  if (!generationId) {
    throw new Error('No generation ID received from Gamma')
  }

  console.log('[GAMMA] Generation started:', generationId)

  // 2. Poll for Completion
  let attempts = 0
  const maxAttempts = 60 // ~2 minutes
  let result = null

  while (attempts < maxAttempts) {
    attempts++
    await new Promise(resolve => setTimeout(resolve, 2000))

    const pollResponse = await fetch(`https://public-api.gamma.app/v1.0/generations/${generationId}`, {
      method: 'GET',
      headers: {
        'X-API-KEY': GAMMA_API_KEY,
        'accept': 'application/json'
      }
    })

    if (!pollResponse.ok) {
      console.warn(`[GAMMA] Poll attempt ${attempts} failed`)
      continue
    }

    const pollData = await pollResponse.json()
    console.log(`[GAMMA] Poll status (${attempts}):`, pollData.status)

    if (pollData.status === 'completed') {
      result = pollData
      break
    } else if (pollData.status === 'error' || pollData.status === 'failed') {
      throw new Error(`Gamma generation failed: ${JSON.stringify(pollData)}`)
    }
  }

  if (!result) {
    throw new Error('Gamma generation timed out')
  }

  const exportUrl = result.exportUrl || result.pdfUrl
  if (!exportUrl) {
    throw new Error('No PDF URL in Gamma response')
  }

  console.log('[GAMMA] PDF ready:', exportUrl)
  return exportUrl
}

// ============================================================
// PDF MERGE WITH PDF.CO
// ============================================================

async function mergePdfs(firstPageUrl: string, gammaUrl: string, orderId: string): Promise<string> {
  console.log('[MERGE] Merging PDFs...')
  console.log('[MERGE] First page:', firstPageUrl)
  console.log('[MERGE] Gamma pages:', gammaUrl)

  const response = await fetch('https://api.pdf.co/v1/pdf/merge', {
    method: 'POST',
    headers: {
      'x-api-key': PDFCO_API_KEY,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      url: `${firstPageUrl},${gammaUrl}`,
      name: `SmartReport_${orderId}_${Date.now()}.pdf`,
      async: false
    })
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`PDF merge failed: ${errorText}`)
  }

  const result = await response.json()

  if (result.error) {
    throw new Error(`PDF.co merge error: ${result.message}`)
  }

  console.log('[MERGE] Merged PDF:', result.url)
  return result.url
}

// ============================================================
// STORAGE & DATABASE
// ============================================================

async function uploadToStorage(
  supabase: any,
  pdfUrl: string,
  orderId: string,
  labId: string
): Promise<string> {
  console.log('[STORAGE] Downloading merged PDF...')

  const pdfResponse = await fetch(pdfUrl)
  if (!pdfResponse.ok) {
    throw new Error('Failed to download merged PDF')
  }

  const pdfBuffer = await pdfResponse.arrayBuffer()

  const timestamp = Date.now()
  const storagePath = `smart-reports/${labId}/${orderId}_${timestamp}.pdf`

  console.log('[STORAGE] Uploading to:', storagePath)

  const { error: uploadError } = await supabase.storage
    .from('reports')
    .upload(storagePath, pdfBuffer, {
      contentType: 'application/pdf',
      cacheControl: '3600',
      upsert: true
    })

  if (uploadError) {
    throw new Error(`Upload failed: ${uploadError.message}`)
  }

  // Get public URL (using custom domain if configured, same as generate-pdf-letterhead)
  const publicUrl = getPublicStorageUrl('reports', storagePath)

  console.log('[STORAGE] Public URL:', publicUrl)
  console.log('[STORAGE] Using custom domain:', !!CUSTOM_REPORTS_DOMAIN)
  return publicUrl
}

async function updateDatabase(supabase: any, orderId: string, pdfUrl: string): Promise<void> {
  console.log('[DB] Updating orders table...')

  const { error } = await supabase
    .from('orders')
    .update({
      smart_report_url: pdfUrl,
      smart_report_generated_at: new Date().toISOString()
    })
    .eq('id', orderId)

  if (error) {
    console.error('[DB] Update failed:', error)
    // Non-fatal - PDF is still accessible
  } else {
    console.log('[DB] Updated successfully')
  }
}

// ============================================================
// MAIN HANDLER
// ============================================================

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { orderId, forceRegenerate } = await req.json()

    if (!orderId) {
      throw new Error('Missing required parameter: orderId')
    }

    console.log('========================================')
    console.log('[SMART REPORT V2] Starting for order:', orderId)
    console.log('[SMART REPORT V2] Force regenerate:', forceRegenerate || false)
    console.log('========================================')

    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    const supabase = createClient(supabaseUrl, supabaseKey)

    // ============================================================
    // CACHING CHECK: Return existing report if available
    // ============================================================
    if (!forceRegenerate) {
      console.log('[CACHE] Checking for existing smart report...')

      const { data: existingOrder, error: orderCheckError } = await supabase
        .from('orders')
        .select('smart_report_url, smart_report_generated_at')
        .eq('id', orderId)
        .single()

      if (!orderCheckError && existingOrder?.smart_report_url) {
        console.log('[CACHE] Found existing report:', existingOrder.smart_report_url)
        console.log('[CACHE] Generated at:', existingOrder.smart_report_generated_at)

        // Verify the URL is accessible (quick HEAD check)
        try {
          const headResponse = await fetch(existingOrder.smart_report_url, {
            method: 'HEAD',
            headers: { 'Accept': 'application/pdf' }
          })

          if (headResponse.ok) {
            console.log('[CACHE] Report URL is valid and accessible')
            return new Response(
              JSON.stringify({
                success: true,
                pdfUrl: existingOrder.smart_report_url,
                cached: true,
                generatedAt: existingOrder.smart_report_generated_at,
                message: 'Returning cached smart report. Use forceRegenerate: true to generate a new one.'
              }),
              {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                status: 200
              }
            )
          } else {
            console.log('[CACHE] Report URL returned', headResponse.status, '- will regenerate')
          }
        } catch (fetchError) {
          console.log('[CACHE] Could not verify URL accessibility:', fetchError)
          // Proceed with regeneration
        }
      } else {
        console.log('[CACHE] No existing smart report found')
      }
    } else {
      console.log('[CACHE] Force regenerate requested - skipping cache check')
    }

    // 1. Fetch Report Context
    console.log('[STEP 1] Fetching report context...')
    const { data: context, error: contextError } = await supabase.rpc(
      'get_report_template_context',
      { p_order_id: orderId }
    )

    if (contextError || !context) {
      throw new Error(`Context fetch failed: ${contextError?.message}`)
    }

    // Get lab_id from order
    const { data: orderData } = await supabase
      .from('orders')
      .select('lab_id')
      .eq('id', orderId)
      .single()

    const labId = orderData?.lab_id || context.order?.lab_id

    // 2. Fetch Letterhead
    console.log('[STEP 2] Fetching letterhead...')
    const letterheadUrl = await fetchLetterheadBackgroundForOrder(supabase, orderId, labId)
    console.log('[STEP 2] Letterhead URL:', letterheadUrl || 'None')

    // 3. Get Lab Info
    const { data: labInfo } = await supabase
      .from('labs')
      .select('name, address, phone, email')
      .eq('id', labId)
      .single()

    // 3b. Fetch Signatory from lab_user_signatures
    console.log('[STEP 3b] Fetching signatory...')
    let signatoryName = ''
    let signatoryImageUrl = ''

    // First try to get from lab_user_signatures (default signature for the lab)
    const { data: labSignature } = await supabase
      .from('lab_user_signatures')
      .select('signature_name, imagekit_url, file_url, variants')
      .eq('lab_id', labId)
      .eq('is_active', true)
      .eq('is_default', true)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle()

    if (labSignature) {
      signatoryName = labSignature.signature_name || ''
      // Prefer optimized variant, then imagekit_url, then file_url
      if (labSignature.variants) {
        const variants = typeof labSignature.variants === 'string'
          ? JSON.parse(labSignature.variants)
          : labSignature.variants
        signatoryImageUrl = variants?.optimized || variants?.webp || ''
      }
      if (!signatoryImageUrl) {
        signatoryImageUrl = labSignature.imagekit_url || labSignature.file_url || ''
      }
      console.log('[STEP 3b] Found signatory:', signatoryName, signatoryImageUrl ? '(with image)' : '(no image)')
    } else {
      console.log('[STEP 3b] No default lab signature found')
    }

    // 4. Extract test group info
    const testGroupIds = context.testGroupIds || []
    let testGroups: { id: string; name: string }[] = []

    if (testGroupIds.length > 0) {
      const { data: tgData } = await supabase
        .from('test_groups')
        .select('id, name')
        .in('id', testGroupIds)

      testGroups = tgData || []
    }

    // Fallback if no test groups
    if (testGroups.length === 0) {
      testGroups = [{ id: 'default', name: 'Laboratory Tests' }]
    }

    // 5. Build First Page Context
    const placeholders = context.placeholderValues || {}
    const firstPageCtx: FirstPageContext = {
      labName: labInfo?.name || placeholders.labName || 'Laboratory',
      labAddress: labInfo?.address || '',
      labPhone: labInfo?.phone || '',
      labEmail: labInfo?.email || '',
      patientName: context.patient?.name || placeholders.patientName || '',
      patientAge: context.patient?.age?.toString() || placeholders.patientAge || '',
      patientGender: context.patient?.gender || placeholders.patientGender || '',
      patientPhone: context.patient?.mobile || context.patient?.phone || '',
      sampleId: context.order?.sampleId || placeholders.sampleId || '',
      orderDate: placeholders.reportDate || new Date().toLocaleDateString('en-IN'),
      collectionDate: placeholders.collectionTime || '',
      doctorName: placeholders.referringDoctor || context.order?.referringDoctorName || '',
      testGroups: testGroups,
      signatoryName: signatoryName,
      signatoryImageUrl: signatoryImageUrl
    }

    // 6. Build Gamma Input Data
    const analytes = context.analytes || []
    const analytesByGroup = new Map<string, AnalyteData[]>()

    // Group analytes by test_group_id
    for (const analyte of analytes) {
      const groupId = analyte.test_group_id || 'ungrouped'
      if (!analytesByGroup.has(groupId)) {
        analytesByGroup.set(groupId, [])
      }
      analytesByGroup.get(groupId)?.push({
        parameter: analyte.parameter || analyte.name || 'Unknown',
        value: analyte.value,
        unit: analyte.unit || '',
        referenceRange: analyte.referenceRange || analyte.reference_range || '',
        flag: analyte.flag || 'Normal',
        interpretation: analyte.interpretation
      })
    }

    // Build test groups data for Gamma
    const testGroupsData: TestGroupData[] = []
    for (const group of testGroups) {
      const groupAnalytes = analytesByGroup.get(group.id) || analytesByGroup.get('ungrouped') || []
      if (groupAnalytes.length > 0) {
        testGroupsData.push({
          id: group.id,
          name: group.name,
          analytes: groupAnalytes
        })
      }
    }

    // If still empty, create a fallback with all analytes
    if (testGroupsData.length === 0 && analytes.length > 0) {
      testGroupsData.push({
        id: 'all',
        name: 'Test Results',
        analytes: analytes.map((a: any) => ({
          parameter: a.parameter || a.name || 'Unknown',
          value: a.value,
          unit: a.unit || '',
          referenceRange: a.referenceRange || a.reference_range || '',
          flag: a.flag || 'Normal'
        }))
      })
    }

    // 7. Get AI Patient Summary for rich content
    console.log('[STEP 7] Getting AI patient summary for rich insights...')

    // Prepare data for AI analysis
    const aiTestGroups = testGroupsData.map(tg => ({
      name: tg.name,
      category: 'Laboratory',
      result_values: tg.analytes.map(a => ({
        analyte_name: a.parameter,
        value: String(a.value),
        unit: a.unit,
        reference_range: a.referenceRange,
        flag: a.flag === 'Normal' ? 'N' : a.flag === 'High' ? 'H' : a.flag === 'Low' ? 'L' : a.flag
      }))
    }))

    const aiSummary = await getAIPatientSummary(
      aiTestGroups,
      {
        age: parseInt(firstPageCtx.patientAge) || undefined,
        gender: firstPageCtx.patientGender || undefined
      }
    )

    // 8. Generate First Page & Gamma Content in Parallel
    console.log('[STEP 8] Generating PDFs in parallel...')

    const firstPageHtml = buildFirstPageHtml(firstPageCtx, letterheadUrl)

    // Use enhanced input if AI summary available, otherwise fallback
    const gammaInput = aiSummary
      ? buildEnhancedGammaInput(testGroupsData, firstPageCtx.patientAge, firstPageCtx.patientGender, aiSummary)
      : buildBasicGammaInput(testGroupsData, firstPageCtx.patientAge, firstPageCtx.patientGender)

    console.log('[STEP 8] Gamma input length:', gammaInput.length, aiSummary ? '(AI-enhanced)' : '(basic)')

    const [firstPageUrl, gammaUrl] = await Promise.all([
      generateFirstPagePdf(firstPageHtml),
      generateGammaContent(gammaInput)
    ])

    // 9. Merge PDFs
    console.log('[STEP 9] Merging PDFs...')
    const mergedUrl = await mergePdfs(firstPageUrl, gammaUrl, orderId)

    // 10. Upload to Storage
    console.log('[STEP 10] Uploading to storage...')
    const publicUrl = await uploadToStorage(supabase, mergedUrl, orderId, labId)

    // 11. Update Database
    console.log('[STEP 11] Updating database...')
    await updateDatabase(supabase, orderId, publicUrl)

    console.log('========================================')
    console.log('[SMART REPORT V2] Complete!')
    console.log('========================================')

    return new Response(
      JSON.stringify({
        success: true,
        pdfUrl: publicUrl,
        mergedUrl: mergedUrl,
        gammaUrl: gammaUrl,
        firstPageUrl: firstPageUrl
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200
      }
    )

  } catch (error) {
    console.error('[SMART REPORT V2] Error:', error)
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400
      }
    )
  }
})
